[tool.ruff]
line-length = 100
target-version = "py39"
extend-exclude = ["data", "artifacts", ".venv"]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # isort
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
